[package]
name = "oso_dev_util_helper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
colored = "*"
toml = { version = "*", features = ["parse"] }

[dev-dependencies]
proptest = "*"

[lints.clippy]
tabs_in_doc_comments = "allow"
