[package]
name = "oso_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
oso_bridge = { path = "../oso_bridge" }
oso_proc_macro = { path = "../oso_proc_macro" }

[features]
rgb = []
bgr = []
bitmask = []
bltonly = []
default = ["bltonly"]
