[package]
name = "oso_dev_util"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "*"
colored = "*"
oso_dev_util_helper = { path = "../oso_dev_util_helper" }
oso_proc_macro = { path = "../oso_proc_macro" }
toml = { version = "*", features = ["parse"] }
